---
title: "Blossom Map"
author: "Alan Millington"
date: "24/03/2021"
output: html_document
---

```{r render-output-doc}
  render("twitter-blossom-watch-2021.Rmd", output_file = 'twitter-blossom-watch-2021.docx')
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
#bbox_cord
#c(-0.170246, -0.034078, -0.034078, -0.170246, 51.564585, 51.564585, 51.6112184, 51.6112184)

ts <- blossom2021 %>% filter(!is.na(bbox_coords)) %>%
    select(bbox_coords)

library(openxlsx)

write.xlsx(blossom2021_geo,"test_bb_geo.xlsx")

```

##Geo-Location of #Blossom Tweets

```{r echo=FALSE, fig.height=12, fig.width=9, message=FALSE, warning=FALSE}
blossom2021 %>%
  mutate(bbox_coords = gsub("\\)|c\\(", "", bbox_coords)) %>%
  separate(bbox_coords, c("box1", "box2","box3","box4", "box5", "box6", "box7", "box8"), sep = ", ") %>%
  mutate_at(c("box1", "box2","box3","box4", "box5", "box6", "box7", "box8"), as.numeric) %>%
    mutate(bbx_long = (box1 + box2 + box3 + box4)/4) %>%
    mutate(bbx_lat = (box5 + box6 + box7 + box8)/4) %>%
  filter(!is.na(place_type)) %>%
  filter(!is.na(media_url)) %>%
  leaflet() %>% 
      setView(lat = 52.8781, lng = -2.8360, zoom = 6) %>%
      addTiles() %>%
          addProviderTiles(providers$Esri.WorldImagery) %>%
 	        addCircleMarkers(lng = ~bbx_long, lat = ~bbx_lat, popup =  ~text, color = "#FF0000", radius = 3, stroke = TRUE, fillOpacity = 0.2)
```


